{
 "title": "Dashboard Jordan",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Server count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(default_http_server_duration_milliseconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Client count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(default_http_client_duration_milliseconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Server bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(default_http_server_duration_milliseconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Client bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(default_http_client_duration_milliseconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}